name: Code Check & Auto Fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整 Git 历史记录（用于检测变更文件）

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      # 1️⃣ 运行 ESLint 检查
      - name: Run ESLint
        run: npx eslint . --ext .js,.ts,.vue

      # 2️⃣ 运行 Prettier 检查（并自动修复）
      - name: Run Prettier check
        run: npx prettier --check . --write  # --write 自动修复问题

      # 3️⃣ 运行 Stylelint 检查（并自动修复）
      - name: Run Stylelint
        run: npx stylelint "**/*.{css,scss,vue}" --fix

      # 4️⃣ 如果有自动修复的变更，提交回仓库
      - name: Commit auto-fixes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix by ESLint/Prettier/Stylelint"
          branch: main
          author_name: GitHub Actions
          author_email: actions@github.com
